name: Github Action Sharing - List all files

on:
  push 

jobs:
  List:
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        run : actions/checkout@v4
      - name : List
        run : ls -al
